name: budgetbuddy
description: "A budget tracking app."
publish_to: 'Nobody in particular'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_slidable: ^4.0.0
  animated_flip_counter: ^0.3.4
  fl_chart: ^0.70.2
  flutter_localization: ^0.3.1
  shared_preferences: ^2.5.2
  table_calendar: ^3.1.3
  logger: ^2.5.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/.
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21